import AppLayout from '../common/components/layouts/AppLayout'
import Container from 'react-bootstrap/Container'
import FlavorText from '../modules/index/components/FlavorText'
import Head from 'next/head'

export default function Index() {
  return (
    <div className="min-vh-100 text-center">
      <Head>
        <title>Your Bot Is</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="d-flex flex-column w-100 min-vh-100 p-3 mx-auto">
        <header className="mb-auto">
          <Container>
            <div className="d-flex align-items-center">
              <span className="h4">Your Bot Is</span>
              <div className="ml-auto">
                <a
                  href="https://github.com/Gulci/yourbot-client"
                  target="_blank"
                  rel="noopener noreferrer">
                  github
                </a>
              </div>
            </div>
          </Container>
        </header>

        <main>
          <Container>
            <h1>your bot is [{<FlavorText />}]</h1>
          </Container>
        </main>

        <footer className="mt-auto text-muted">
          client by{' '}
          <a
            href="https://github.com/gulci"
            target="_blank"
            rel="noopener noreferrer">
            gulci
          </a>
        </footer>
      </div>
    </div>
  )
}

Index.getLayout = (page) => <AppLayout hideNav={true}>{page}</AppLayout>
